version: '3'
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: "mysql-db"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
      - ./db/my.conf:/etc/mysql/conf.d/my.cnf
      # sqlを共有
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306