version: '3'
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: "mysql-db"
    environment:
      # rootのパスワードを設定
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      # DBを作成
      MYSQL_DATABASE: book
      # ユーザ作成
      MYSQL_USER: docker
      MYSQL_PASSWORD: ${DB_USER_PASS}
    volumes:
      # データ永続化
      - ./data:/var/lib/mysql
      # 設定ファイル共有
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      # 初期データをマウントする場所,sqlを共有
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"